### ISSUE TITLE
Any way to disable US EPA corrections

### ISSUE THREAD

**Issue by pverscha** [chaunceygardiner/weewx-airlink#4]
Hi,

First of all, thank you for this extension! I've just recently bought a Davis Airlink and I was able to integrate it with my existing WeewX installation easily. Now, I noticed that the PM2.5 values reported to WeewX by this extension are different from the ones that are reported by the Davis Weatherlink app. This is most probably the result of the US EPA correction that's automatically applied by this plugin. I would, however, like to keep track of the original value (as reported by the sensor). Is there any way to easily disable this correction?

Thanks!

**Comment by chaunceygardiner** [comment]
Hi Peter,

As a design decision, I made this plug-in work with WeeWX’s extended schema, rather than require columns to be added to the database or use a separate database.  This decision, which was done for ease of use, combined with the EPA formula using other AirLink readings that don’t have a place in the database, is the reason why the original value isn’t stored.  The EPA corrected value simply can’t be calculated without the AirLink’s humidity and temperature, so I do the correction right away, when I have the values.

I understand you might want the original values for record keeping.  I store all values from the AirLink separately outside of WeeWX using another piece of software I wrote (airlink-proxy).  If you really want to use this extension, and you really want the original value, you can modify the code (but you’ll lose the EPA corrected value and you won’t be able to recreate it).

Make this change in airlink.py:

Current code:
    @staticmethod
    def compute_pm_2p5_us_epa_correction(pm_2p5: float, hum: float, temp: float) -> float:
        # PM2.5=0.541*PA_cf_1-0.0618*RH +0.00534*T +3.634
        val = 0.541 * pm_2p5 - 0.0618 * hum + 0.00534 * temp + 3.634
        return val if val >= 0.0 else 0.0

Change to:
    @staticmethod
    def compute_pm_2p5_us_epa_correction(pm_2p5: float, hum: float, temp: float) -> float:
        # Make no correction, just return pm_2p5
        return pm_2p5

I thought about storing the extra values by reusing unused columns, but that isn’t so attractive.  Tom Keefer is currently looking at making it much easier for the end user to add columns to the archive table.  When that is released, I’ll have another look at this and perhaps extend the schema to retain the original values.

**Comment by jshatch** [comment]
Please clarify the difference between the original values and the EPA corrected values.  Right now my AQI as reported by WeeWX is 80 but the value reported by WeatherLink is 139.  That’s a very big difference and I don’t know which number is correct.  The other sensors around me (PurpleAir) are closer to the 130’s.

**Comment by chaunceygardiner** [comment]
You can read more about the EPA correction here:
https://cfpub.epa.gov/si/si_public_record_Report.cfm?dirEntryId=349513&Lab=CEMM
https://cfpub.epa.gov/si/si_public_file_download.cfm?p_download_id=540979&Lab=CEMM

As for comparing the Airlink to PurpleAir, I do it all the time since I run both.  I view a 24 hour graph of the two every morning.  They normally track reasonably closely.  You do need to select the EPA correction in the PurpleAir readings, for example, at my location:
https://www.purpleair.com/map?opt=1/i/mAQI/a0/cC5&select=41485#18.13/37.431132/-122.111384
In the link above, note that the US EPA PM2.5 AQI layer is selected and the US EPA conversion is selected.

As for why I am using the EPA correction, it’s because it’s much better.  Just read up in the first two links.

The PurpleAir sensor has the advantage of having two sensors that can be averaged.  As such, spikes in one of the sensors is dampened by the other.  Alas, the Airlink only has one sensor.
